-- ============================================================
-- 🔧 일차방정식 릴레이 배틀 전용 테이블
-- ============================================================

-- 1. 방 정보 테이블
CREATE TABLE IF NOT EXISTS public.relay_rooms (
  id TEXT PRIMARY KEY,           -- '1-1', '1-2' 등 반 번호
  status TEXT DEFAULT 'waiting', -- 'waiting', 'playing', 'ended'
  team_count INTEGER DEFAULT 4,  -- 3~7팀
  timer_duration INTEGER DEFAULT 120, -- 초 단위 (2분)
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. 팀별 진행 상태 테이블
CREATE TABLE IF NOT EXISTS public.relay_teams (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id TEXT REFERENCES public.relay_rooms(id) ON DELETE CASCADE,
  team_name TEXT,                -- '1팀', '2팀' 등
  score INTEGER DEFAULT 0,
  current_question JSONB,        -- { equation: "2x+3=7", answer: 2, level: "normal" }
  status TEXT DEFAULT 'ready',   -- 'ready', 'playing', 'switching'
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(room_id, team_name)
);

-- RLS 활성화
ALTER TABLE public.relay_rooms ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.relay_teams ENABLE ROW LEVEL SECURITY;

-- 정책 (보안 정책은 단순화하여 익명 접근 허용)
CREATE POLICY "Allow All Access" ON public.relay_rooms FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow All Access" ON public.relay_teams FOR ALL USING (true) WITH CHECK (true);
